#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'
touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
