#!/usr/bin/env bash
#Install nginx  on web server;Nginx should be listening on port 80

# Update the package list
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a default HTML file with "Hello World!" content
touch /var/www/html/index.html
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Make sure the HTML file is readable by Nginx
sudo chmod 644 /var/www/html/index.html
sudo chown www-data:www-data /var/www/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html

echo "server {
        listen  80;
        listen  [::]:80 default_server;
        root    /etc/nginx/html;
        index   index.html index.htm;
}" > /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx reload
