#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
# Bug: sudo nginx status returns 'not running'; netstat -lpn does not show port 80
# Solution: https://stackoverflow.com/questions/16021481/nginx-not-listening-to-port-80


rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
